/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pa_restc_util_JniUtil */

#ifndef _Included_com_pa_restc_util_JniUtil
#define _Included_com_pa_restc_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pa_restc_util_JniUtil
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pa_restc_util_JniUtil_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
